### PR TITLE
Fix deprecations

### LINKED ISSUE #50: Add requiresSQLCommentHint to custom doctrine types
Hi! Can you add overrided `requiresSQLCommentHint()` into all types?
```
User Deprecated: The type "text[]" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "MartinGeorgiev\Doctrine\DBAL\Types\TextArray::requiresSQLCommentHint().
```

### PR DESCRIPTION
**Pull request by GawainLynch**
* Add requiresSQLCommentHint() to BaseType

See doctrine/DoctrineBundle#947
Fixes #50 

* Drop null parameter on call to TestCase->setMethods()

The method is type hinted to `array` so `null` is throwing a type error

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,3 +1,4 @@
 bin/
 vendor/
 composer.lock
+.phpunit.result.cache
```
Comment (martin-georgiev) [inline .gitignore]: I'd prefer this to be added in developer's global `.gitignore`.

File: src/MartinGeorgiev/Doctrine/DBAL/Types/BaseType.php [hunk 2]
```diff
@@ -32,6 +32,14 @@ public function getName(): string
         return static::TYPE_NAME;
     }
 
+    /**
+     * {@inheritdoc}
+     */
+    public function requiresSQLCommentHint(AbstractPlatform $platform)
```
Comment (martin-georgiev) [inline src/MartinGeorgiev/Doctrine/DBAL/Types/BaseType.php]: Can you please force a return type?

File: tests/MartinGeorgiev/Doctrine/DBAL/Types/BaseTypeTest.php [hunk 3]
```diff
@@ -26,7 +26,7 @@ protected function setUp(): void
         $this->platform = $this->createMock(AbstractPlatform::class);
 
         $this->fixture = $this->getMockBuilder(BaseType::class)
-            ->setMethods(null)
+            ->setMethods()
```
Comment (martin-georgiev) [inline tests/MartinGeorgiev/Doctrine/DBAL/Types/BaseTypeTest.php]: I'm not sure why this change is needed.

File: .gitignore (hunk 1 above)
Comment (GawainLynch) [reply .gitignore]: WFM! :+1:

File: tests/MartinGeorgiev/Doctrine/DBAL/Types/BaseTypeTest.php (hunk 3 above)
Comment (GawainLynch) [reply tests/MartinGeorgiev/Doctrine/DBAL/Types/BaseTypeTest.php]: PHPUnit type hints this to `array` (not `?array`) and passing `null` is throwing a type error

File: src/MartinGeorgiev/Doctrine/DBAL/Types/BaseType.php (hunk 2 above)
Comment (GawainLynch) [reply src/MartinGeorgiev/Doctrine/DBAL/Types/BaseType.php]: Done

File: tests/MartinGeorgiev/Doctrine/DBAL/Types/BaseTypeTest.php (hunk 3 above)
Comment (GawainLynch) [reply tests/MartinGeorgiev/Doctrine/DBAL/Types/BaseTypeTest.php]: In true Sunday morning style, the original commit of mine was also wrong, it needs an empty array passed.

**Comment by Gemorroj** [comment]
Can you explain why I still have this error?
```
The type "jsonb" was implicitly marked as commented due to the configurati
on. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the
 "commented" attribute in the configuration to "false" or mark the type as comme
nted in "MartinGeorgiev\Doctrine\DBAL\Types\Jsonb::requiresSQLCommentHint().
```

**Comment by martin-georgiev** [comment]
> Can you explain why I still have this error?
> 
> ```
> The type "jsonb" was implicitly marked as commented due to the configurati
> on. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the
>  "commented" attribute in the configuration to "false" or mark the type as comme
> nted in "MartinGeorgiev\Doctrine\DBAL\Types\Jsonb::requiresSQLCommentHint().
> ```

Can you please share more details about the relevant packages you use?

**Comment by Gemorroj** [comment]
@martin-georgiev 
I use Symfony 4.4 and with tests got noties:
```
Other deprecation notices (15)

  1x: The type "jsonb" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "MartinGeorgiev\Doctrine\DBAL\Types\Jsonb::requiresSQLCommentHin
t()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The type "jsonb[]" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "MartinGeorgiev\Doctrine\DBAL\Types\JsonbArray::requiresSQLCom
mentHint()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The type "smallint[]" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "MartinGeorgiev\Doctrine\DBAL\Types\SmallIntArray::requires
SQLCommentHint()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The type "integer[]" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "MartinGeorgiev\Doctrine\DBAL\Types\IntegerArray::requiresSQ
LCommentHint()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The type "bigint[]" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "MartinGeorgiev\Doctrine\DBAL\Types\BigIntArray::requiresSQLC
ommentHint()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The type "text[]" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "MartinGeorgiev\Doctrine\DBAL\Types\TextArray::requiresSQLComme
ntHint()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The type "carrier_service" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "App\DBAL\Types\CarrierServiceType::requiresSQLComment
Hint()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The type "shipping_segment_condition_value" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "App\DBAL\Types\ShippingSegmentCondit
ionValueType::requiresSQLCommentHint()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The type "website_metadata_categories" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "App\DBAL\Types\WebsiteMetadataCategoriesT
ype::requiresSQLCommentHint()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The type "website_metadata_product_attributes" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "App\DBAL\Types\WebsiteMetadataPro
ductAttributesType::requiresSQLCommentHint()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The type "shipping_rule_action" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "App\DBAL\Types\ShippingRuleActionType::requiresS
QLCommentHint()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The type "volumetric_weight_separate_dimensions" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "App\DBAL\Types\VolumetricWeight
SeparateDimensionsType::requiresSQLCommentHint()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The type "volumetric_weight_volume" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "App\DBAL\Types\VolumetricWeightVolumeType::r
equiresSQLCommentHint()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The type "volumetric_weight_volumetric_weight" was implicitly marked as commented due to the configuration. This is deprecated and will be removed in DoctrineBundle 2.0. Either set the "commented" attribute in the configuration to "false" or mark the type as commented in "App\DBAL\Types\VolumetricWeightVo
lumetricWeightType::requiresSQLCommentHint()."
    1x in RatesTest::testRates from App\Tests\Api

  1x: The "Doctrine\Bundle\DoctrineBundle\Registry" class implements "Symfony\Bridge\Doctrine\RegistryInterface" that is deprecated since Symfony 4.4, use Doctrine\Common\Persistence\ManagerRegistry instead.
```

test file:
```php
<?php

namespace App\Tests\Api;

use App\Entity\Origin;
use App\Entity\Website;
use App\Model\Api\Rates\Product;
use App\Model\Api\Rates\Result\Carrier;
use App\Model\Api\Rates\Result\CarrierService;
use App\Model\Api\Rates\Result\Origin as ResultOrigin;
use App\Model\Api\Rates\Shipping;
use App\Service\RatesCalculator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class RatesTest extends KernelTestCase
{
    public function testRates(): void
    {
        self::bootKernel();
        $ratesCalculator = self::$container->get(RatesCalculator::class);
        $entityManager = self::$container->get(EntityManagerInterface::class);

        $shipping = new Shipping();
        $shipping->setWebsite($entityManager->getRepository(Website::class)->findOneBy([]));
        $shipping->setCompanyName('company name');
        $shipping->setCountry('GB');
        $shipping->setPostalCode('NW1 0UR');
        $shipping->setCity('London');
        $shipping->setAddress('32 Guild Street');
        $shipping->setRegionCode('England');
        $shipping->setRegionName('England');
        $shipping->setContactPhone('+4407883307480');
        $shipping->setProducts([
            (new Product())
                ->setQuantity(1.0)
                ->setPriceWithTax(20.0)
                ->setPriceWithoutTax(20.0)
                ->setOrigin($entityManager->getRepository(Origin::class)->findOneBy([]))
                ->setWeight(1.0),
        ]);

        $result = $ratesCalculator->calculate($shipping);

        /** @var ResultOrigin $resultOrigin */
        $resultOrigin = $result->first();
        /** @var Carrier|false $carrier */
        $carrier = $resultOrigin->getCarriers()->first();
        $this->assertNotFalse($carrier);

        $this->assertTrue($carrier->isSuccess());
        /** @var CarrierService|false $service */
        $service = $carrier->getServices()->first();
        $this->assertNotFalse($service);
        $this->assertTrue($service->isSuccess());
    }
}
```

composer:
```
    "require": {
        "php": "^7.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ext-apcu": "*",
        "ext-pdo_pgsql": "*",
        "ext-curl": "*",
        "ext-json": "*",
        "ext-intl": "*",
        "symfony/console": "4.4.*",
        "symfony/dotenv": "4.4.*",
        "symfony/flex": "^1.4.8",
        "symfony/framework-bundle": "4.4.*",
        "symfony/yaml": "4.4.*",
        "symfony/http-client": "4.4.*",
        "symfony/orm-pack": "*",
        "symfony/validator": "4.4.*",
        "symfony/security-bundle": "4.4.*",
        "symfony/intl": "4.4.*",
        "symfony/form": "4.4.*",
        "symfony/serializer-pack": "*",
        "symfony/monolog-bundle": "^3.5",
        "symfony/mercure-bundle": "^0.2",
        "misd/phone-number-bundle": "^2.0@dev",
        "nelmio/api-doc-bundle": "^3.5",
        "nelmio/cors-bundle": "^1.5",
        "lexik/jwt-authentication-bundle": "^2.6",
        "lcobucci/jwt": "^3.3",
        "martin-georgiev/postgresql-for-doctrine": "^1.2",
        "beberlei/doctrineextensions": "^1.2",
        "fresh/doctrine-enum-bundle": "^6.6",
        "barbieswimcrew/zip-code-validator": "^1.3",

        "symfony/mailer": "4.4.*",
        "symfony/twig-pack": "*",

        "shapecode/cron-bundle": "^3.2.3",
        "pagerfanta/pagerfanta": "^2.1"
    },
    "require-dev": {
        "symfony/phpunit-bridge": "4.4.*",
        "doctrine/doctrine-fixtures-bundle": "^3.3",
        "symfony/maker-bundle": "^1.14",
        "symfony/debug-bundle": "4.4.*",
        "easycorp/easy-log-handler": "^1.0.9",
        "phpstan/phpstan-symfony": "^0.10",
        "phpstan/phpstan-phpunit": "^0.10",
        "friendsofphp/php-cs-fixer": "^2.16"
    },
```
